mysite/iss/urls.py
from django.urls import path
from . import views

app_name = 'iss'

urlpatterns = [
	path('', views.home, name='home'),
	path('live/', views.live, name='live'),
	path('passtime/', views.passtime, name='passtime'),
	path('more/', views.more, name='more')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('iss.urls'))
]

mysite/iss/models.py
from django.db import models

# Create your models here.

mysite/iss/views.py
from django.shortcuts import render
import time
from .services import apod

# Create your views here.
def home(request):
	return render(request, 'iss/home.html')

def live(request):
	return render(request, 'iss/live.html')
	
def passtime(request):
	return render(request, 'iss/passtime.html')

# def isspassdata(request, data):
# 	lati = data['Lati']
# 	longi = data['Longi']
# 	return render(request, 'iss/passtime.html')

def more(request):
	variable = apod()
	context = {'value':variable}
	return render(request, 'iss/more.html', context)

mysite/iss/templates/iss/base.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
	<head>
		<meta charset="utf-8">
		<title>Track-S</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
   	    <link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet">
   		<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
	</head>
	<body>
		<div class='page-header'>
			<h1><a href="{% url 'iss:home' %}">Track-S</a></h1>
		</div>
		<div class='container'>
			{% block content %}
			{% endblock %}
		</div>
	</body>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		{% block javascript %}
		{% endblock %}

		<!-- <script type="text/javascript">
			$(document).ready( function() {
							for (var i = 0; i < 400; i++) {
  var star = '<div class="star" style="animation: twinkle '+((Math.random()*5) + 5)+'s linear '+((Math.random()*5) + 5)+'s infinite; top: '+Math.random()*$(document).height()+'px; left: '+Math.random()*$(document).width()+'px;"></div>';
  $('body').append(star);
}
			})

		</script> -->
</html>

mysite/iss/templates/iss/home.html
{% extends 'iss/base.html' %}
{% load static %}
{% block content %}
	<!-- <div class='main-image'>
		<img src="{% static 'images/iss-bg.jpg'%}">
	</div> -->
	<div class='row' style="padding-top: 50px; text-align: center;">
		<div class='col-sm'>
			<div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{% static 'images/live.jpg'%}" alt="Card image cap">
			  <div class="card-body">
			    <!-- <h5 class="card-title">Live Position</h5> -->
			    <a href="{% url 'iss:live' %}" class="btn btn-primary">Live Position</a>
			  </div>
			</div>
		</div>
		<div class='col-sm' >
			<div class="card" style="position: center; width: 18rem;">
			  <img class="card-img-top" src="{% static 'images/location.jpg'%}" alt="Card image cap">
			  <div class="card-body">
			    <!-- <h5 class="card-title">At Your Location</h5> -->
			    <a href="{% url 'iss:passtime' %}" class="btn btn-primary">At Your Location</a>
			  </div>
			</div>
		</div>
		<div class='col-sm' >
			<div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{% static 'images/info (3).jpg'%}" alt="Card image cap">
			  <div class="card-body">
			    <!-- <h5 class="card-title">Weekly Blogs</h5> -->
			    <a href="{% url 'iss:more' %}" class="btn btn-primary">Weekly Blogs</a>
			  </div>
			</div>
		</div>
	</div>
{% endblock %}

mysite/iss/templates/iss/live.html
{% extends 'iss/base.html' %}
{% load static %}

{% block content %}
	<div>
		<div id='mapid'></div>	
	</div>
	<div style="margin-top: 50px; text-align: center; font-family: 'Special Elite', cursive; color: white;">
		<h4>Latitude<h5 id='show'></h5></h4>
		<br>
		<h4>Longitude<h5 id='shoow'></h5></h4>
	</div>

	<!-- <script src='https://code.jquery.com/jquery-3.5.1.min.js'></script> -->
{% endblock %}

{% block javascript %}
	<script src="{% static 'javascript/jquery-3.5.1.js' %}"></script>
	<script src="{% static 'javascript/isslive.js'%}"></script>
{% endblock %}

mysite/iss/templates/iss/more.html
{% extends 'iss/base.html' %}
{% load static %}
{% block content %}
	<div class='row' style="padding-top: 50px; text-align: center;">
		{% for i in value %}
			<!-- <li><a href="{{i.1}}">{{i.0}}</a></li> -->
		<div class='col-sm' style=" filter: drop-shadow(0 0 12px #2e2d2d)">
			<div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{{i.2}}" alt="Card image cap">
			  <div class="card-body">
			    <h5 class="card-title">{{i.0}}</h5>
			    <a href="{{i.1}}" class="btn btn-primary">Read it..</a>
			  </div>
			</div>
		</div>

		{% endfor %}




	</div>
{% endblock %}

mysite/iss/templates/iss/passtime.html
{% extends 'iss/base.html' %}
{% load static %}

{% block content %}
	<div id='mapid'>
	
	</div>	
	<div id='isspass' style="text-align: center; font-family: 'Special Elite', cursive; color: white; margin-top: 30px;" ></div>
    <!-- 
	<script src="{% static 'javascript/jquery-3.5.1.js' %}"></script>
	<script src="{% static 'javascript/isspass.js'%}"></script> -->    
	<!-- was doing this mistake to include it here -->
{% endblock %}

{% block javascript %}
	<script src="{% static 'javascript/jquery-3.5.1.js' %}"></script>
	<script src="{% static 'javascript/isspass.js'%}"></script>
{% endblock %}